"""Initial

Revision ID: 5891aebe3521
Revises:
Create Date: 2023-08-01 10:57:48.159073

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '5891aebe3521'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'dish',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'name',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            'text',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'ingredient',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'name',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            'measure_unit',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'dishingredientamount',
        sa.Column('dish_id', sa.Integer(), nullable=False),
        sa.Column('ingredient_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['dish_id'], ['dish.id']),
        sa.ForeignKeyConstraint(
            ['ingredient_id'],
            ['ingredient.id'],
        ),
        sa.PrimaryKeyConstraint('dish_id', 'ingredient_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dishingredientamount')
    op.drop_table('ingredient')
    op.drop_table('dish')
    # ### end Alembic commands ###
